/**
 * @param {string} word
 * @return {number}
 */
var countVowels = function (word) {
  let ans = 0n;
  const isVowel = (s) => 'aeiou'.includes(s);
  const totalLength = BigInt(word.length);
  for (let i = 0n; i < totalLength; i++) {
    const char = word[i];
    if (!isVowel(char)) continue;
    const length = totalLength - i;
    const number = i + 1n;
    const total = length * number;
    ans += total;
  }
  return Number(ans);
};

console.log(countVowels('aba'));
console.log(countVowels('abc'));
console.log(countVowels('ltcd'));
console.log(countVowels('noosabasboosa'));
console.log(
  countVowels(
    'abaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaabasaabaabasabaabaabaabasaasasabaaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaabasaabaabasabaabaabaabasaasasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaabasaabaabasabaabaabaabasaasasabaabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaabasaabaabasabaabaabaabasaasabaabaababaabasabaabaabaabasaabaabasabaabaabaabasaabaabasabaabaabaabasaasaabaabasabaabaabaabasaabaabasabaabaabaabasaasa'
  )
);
